import type { Metadata } from "next";
import { Geist, Geist_Mono, Jost } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider/theme-provider";
import { Toaster } from 'sonner';
import Providers from "@/providers/Providers";
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const jost = Jost({
  subsets: ['latin'], // Specify the subset
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'], // Optional: Specify font weights
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.className} ${geistMono.className} ${jost.className} antialiased`}
      >
        <Providers>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          {children}
          <Toaster position="top-center" richColors />
        </ThemeProvider>
        </Providers>
      </body>
    </html >
    
  );
}
